### ISSUE TITLE
Development discussion

### ISSUE THREAD

**Issue by Alovchin91** [Alovchin91/vorbis-winrt#1]
Welcome to the development discussion of **Ogg Vorbis for Windows Runtime** project.
Here we discuss the development process of the project and all related stuff. If you think you could help, feel free to collaborate!

**Comment by Alovchin91** [comment]
@mcosmin222 So, first of all here goes the original [libvorbis project](http://xiph.org/vorbis/). They actually have two dev libraries: _libvorbis_ that provides low-level APIs to work with Vorbis files, and _libvorbisfile_ that exposes a high-level API to work with files and streams. I think we should stick with _libvorbisfile_, at least for now.

And yes, I think we could use some code from your managed Ogg decoder, though I'm not sure if this is necessary ) Let's see how it goes. For example, I used FlacBox only for WaveInputStream and packing FLAC int[][] samples into an IBuffer.

**Comment by brabebhin** [comment]
The managed codec is called MonoVorbis.

https://github.com/mono/csvorbis

Where can one find libvorbisfile?

**Comment by Alovchin91** [comment]
@mcosmin222 libvorbisfile is part of libvorbis source code. Just download ZIP file and it will be there :)

**Comment by Alovchin91** [comment]
Hey, I commited the base solution for the project. For now it contains only the original _libvorbis_ that successfully builds for Windows Phone. If you have already started some work, please pull this commit and merge. Thanks!

**Comment by brabebhin** [comment]
Hey. I can't do much for the next 2 or 3 days. I am rather busy with collage projects.

**Comment by Alovchin91** [comment]
@mcosmin222 No problem, just be aware :)

**Comment by brabebhin** [comment]
I get all notifications in the email feed. If you manage to create the wrapper, I will make the MSS.

**Comment by Alovchin91** [comment]
@mcosmin222 Yeah, I take the wrapper. Though I'll try to make it as compatible as possible, so we could have one universal MSS for all codecs. I think we need an interface (say, IMediaDecoder) that will abstract codecs from MSS, and implement this high-level IMediaDecoder for each codec.

**Comment by brabebhin** [comment]
Or we can create a high level class which will have a CreateMediaStreamSource method and that in turn will expose the underlaying media stream sources which are hidden from the developer and probably different from one another. This way we don't have to worry about inheritance.

**Comment by brabebhin** [comment]
hey. how's it going? ima take a look at the code so far tomorrow ^^

**Comment by Alovchin91** [comment]
@mcosmin222 Hey! I'm currently finishing WinRT wrapper, but I haven't tested it yet. I'll commit it in a couple of hours, I think, so you can use it tomorrow ;) By the way, it seems we won't need any kind of `WaveInputStream` in Vorbis, it allows to specify desired buffer size.

**Comment by brabebhin** [comment]
That's nice. I will test it tomorrow and see what happens. If all goes well I should post the mss by sunday:p

**Comment by Alovchin91** [comment]
@mcosmin222 
Alright, so I have commited the WinRT project. Please be aware that is it **completely untested**, so I cannot even guarantee that it works. It is a nightly build (you know, it's night now here :D). This commit creates a base from where we can now start branching.

Now, I want to ask you to create a separate branch for MediaStreamSource and all that stuff, so we could keep the code organized. I will also create a new dev branch where I will test the WinRT project and fix issues. We will then merge the branches to master altogether.

Thanks!

**Comment by brabebhin** [comment]
Ok. I built the wrapper and integrated it in my app. Now it is time to build the MSS and test the thing in the emulator^^

**Comment by brabebhin** [comment]
Well it seems I can't get past the OggVorbisFile.open(iRandomAccessStream, ibuffer) method. It just keeps throwing System.Exception regardless of buffer size.

**Comment by Alovchin91** [comment]
@mcosmin222 What is the HRESULT of the exception?

**Comment by brabebhin** [comment]
Give me a second^^

**Comment by brabebhin** [comment]
-132 is the HRESULT

**Comment by Alovchin91** [comment]
@mcosmin222 Yeah, I see. Here comes the first bug :)

Commited the fix.

**Comment by Alovchin91** [comment]
Aaaaand here comes another fix for VorbisInfo class... :)

**Comment by brabebhin** [comment]
I'll take a look in a few hours. Gotta fix something else till then.

**Comment by Alovchin91** [comment]
@mcosmin222 Okay, so now it plays correctly :) I'll try to figure out one thing and will post here the example usage.

**Comment by brabebhin** [comment]
Nah. My current endevor has nohing to do with this project xD I will finish that and get back to this.

**Comment by Alovchin91** [comment]
@mcosmin222 I understand :) That wasn't regarding your fix to something, it was about the latest commit :)

**Comment by Alovchin91** [comment]
Okay, so here's the sample usage. I won't describe MediaStreamSource as it is as easy as can be and almost completely copied from [FLAC for Windows Runtime](https://github.com/Alovchin91/flac-winrt), except that it doesn't even need `WaveInputStream` (and FLAC project will also get rid of it soon).

So, assume you have a managed `VorbisMediaDecoder` class with `OggVorbisFile _vorbisFile` field that is supposed to help you wrap all the decoder logic. Here's how you initialize the decoder:

```
public void Initialize(IRandomAccessStream fileStream)
{
    this._vorbisFile.Open(fileStream, null);

    if (!this._vorbisFile.IsValid)
        throw new InvalidOperationException();
}
```

Simple, ah? :) Note that if something goes wrong, the `OggVorbisFile.Open()` method will throw an exception with HResult equal to one of libvorbis' [return codes](http://xiph.org/vorbis/doc/libvorbis/return.html). **This behavior is under consideration, but what makes it harder to decide is that Windows Runtime doesn't support custom exceptions.** Still it's a recommended practice to check for `OggVorbisFile.IsValid` each time you call `OggVorbisFile` API.

Now, to create a `MediaStreamSource` you will need these four properties of media stream: sample rate, channel count, bits per sample count and duration. Here's how you can get those:

```
var info = this._vorbisFile.Info(-1);
var sampleRate = Convert.ToUInt32(info.Rate);
var channelCount = Convert.ToUInt32(info.Channels)
var bitsPerSample = 16; // !
var duration = this._vorbisFile.TimeTotal(-1);
```

Note those `-1` parameters: they allow to receive info about the whole physical bitstream instead of separate logical bitstreams withing an OGG file. I'll make overloads for these methods in the next commit. Also note that bits per sample is set to 16. Actually, OGG supports 8 and 16 bit samples, but at least currently Windows Runtime class hardcodes 16 bit samples (it is done in `OggVorbisFile.Read` method, on `::ov_read` call - you can see parameters `2, 1` there - it's 2 byte = 16 bit samples with big endian encoding that is needed for MSS). You can change this value of course, but note that even good quality files will have not-such-good quality then.

Finally, what you will need when you will report samples to MSS, is the length of the sample. Since actually buffer size is established by Ogg Vorbis codec, and moreover there might be VBR files, you shouldn't hardcode this value. Here's how you can get it (just like in FLAC's `WaveInputStream`):

```
public double GetDurationFromBufferSize(uint bufferSize)
{
    MediaStreamInfo streamInfo = this.GetStreamInfo();

    if (streamInfo.BytesPerSecond == 0)
        return 0;

    return (double)bufferSize / streamInfo.BytesPerSecond;
}
```

I hope this helps :)

**Seeking is not yet implemented.**

**Comment by brabebhin** [comment]
Well, the API seems to simply be a C version of the MonoVorbis project I linked above. It even has the same function name & the like. 

I estimate I will be back on this in 2-3 hours. ^^

**Comment by Alovchin91** [comment]
@mcosmin222 I haven't seen the MonoVorbis actually, I just took the original libvorbisfile and implemented an adapter for its functions :) The name of the main class (OggVorbisFile) is actually an adaptation of the name of OggVorbis_File struct that is used in all vorbisfile's funcs, and the names of the methods are adaptations of vorbisfile's funcs names as well )

**Comment by Alovchin91** [comment]
Updated an API. Now `Read` method _returns_ the IBuffer instead of accepting it as an out parameter, and most methods that accept `int bitstream` now have overloads without it. See README.md.

**Comment by brabebhin** [comment]
What's the problem with seeking?

**Comment by brabebhin** [comment]
Meh >.<

A first chance exception of type 'System.OutOfMemoryException' occurred in NativeMediaStreamSources.DLL

Additional information: Not enough storage is available to complete this operation.

In the last freeking second of the song.
_goes in a corner and cries_

nevermind that. Didn't put the stop condition in the sample requested event. I will upload a file with the MSS.

**Comment by Alovchin91** [comment]
@mcosmin222 The problem with seeking is that I... um... forgot about it :D I will implement it and commit in a couple of hours. Now please don't forget to use another branch for MSS, we will merge them later! Thanks :)

**Comment by brabebhin** [comment]
I have no idea how to make a new branch xD

**Comment by Alovchin91** [comment]
@mcosmin222 Wow, are you sure it was supposed to be so? :) Do you use VS 2013?

**Comment by brabebhin** [comment]
yup. why?

**Comment by Alovchin91** [comment]
@mcosmin222 Then you can clone a repository and work with it from VS :) I see you just created a new file and uploaded a content there, don't do that :)

**Comment by brabebhin** [comment]
Well the problem is i work directly from my app so it is kinda difficult to do this from visual studio xD

**Comment by brabebhin** [comment]
Don't worry, next time I will just post it here xD

**Comment by Alovchin91** [comment]
@mcosmin222 Okay, but don't commit it that way ;) Create a Wiki page instead.
If you decide to do that from Visual Studio, here's how you can clone repository:
![vs2013git](https://cloud.githubusercontent.com/assets/8490695/4780785/6f0e2142-5c78-11e4-9881-44cbdda601ee.jpg)
And then when you open the repository in VS, select branches, select Create branch and create a new branch from master (not origin/master!).

**Comment by Alovchin91** [comment]
@mcosmin222 If you don't mind, please, remove the file from the root directory ;) and make a Wiki page instead. Thanks :)

**Comment by Alovchin91** [comment]
@mcosmin222 No need to post it here, post it to the wiki and give a link in README.md, for example :)

**Comment by brabebhin** [comment]
Github is really weird xD

**Comment by Alovchin91** [comment]
@mcosmin222 Alright, I removed that file from the root and updated wiki with its contents. Please try to avoid committing anything to master branch except bug fixes :) I'll update readme in the morning cause I can't do this properly from the phone.

**Comment by Alovchin91** [comment]
Seeking is here. Take it, use it :)

**Comment by brabebhin** [comment]
Good...good...I shall put it to good use. Once my internet is back.

**Comment by brabebhin** [comment]
Ok so i downloaded the API and there is no extra methods for seeking.

**Comment by Alovchin91** [comment]
@mcosmin222 Umm... there's a bunch of new methods actually :)

``` cpp
void RawSeek(ogg_int64_t pos);
void PcmSeek(ogg_int64_t pos);
void TimeSeek(double pos);
void PcmSeekPage(ogg_int64_t pos);
void TimeSeekPage(double pos);

void RawSeekLap(ogg_int64_t pos);
void PcmSeekLap(ogg_int64_t pos);
void TimeSeekLap(double pos);
void PcmSeekPageLap(ogg_int64_t pos);
void TimeSeekPageLap(double pos);
```

Are you sure you have rebuilt the project?

**Comment by brabebhin** [comment]
Yes. For some reason, the changes weren't available when I first downloaded them. On second try they all showed up. I will update the MSS from wiki. It works fine.

**Comment by Alovchin91** [comment]
@mcosmin222 Glad to hear that )

**Comment by brabebhin** [comment]
Done :)

**Comment by Alovchin91** [comment]
**Breaking change is coming!**
Not so breaking, actually, but you definitely should take it into account.
The root namespace _libvorbisfile_ will be moved to the namespace **_Vorbisfile.WindowsRuntime_**. The output files (.dll and .winmd) will be renamed respectively. I think everybody would agree that this will make the project's naming more Windows compliant and will indicate the actual goal of the project.
