### ISSUE TITLE
sooo...

### ISSUE THREAD

**Issue by brabebhin** [Alovchin91/vorbis-winrt#2]
What's next captain? 

This interesting thing we had going on here gave me a nice idea while enjoying my chicken soul (I always have great ideas when eating soup).

I COULD create an equalizer framework to apply effects to media stream sources...

**Comment by Alovchin91** [comment]
@mcosmin222 Well, that's an interesting question. For now, I think the next step would be to make the similar implementation of Opus codec wrapper, and then combine all three in the single repository and actually create an infrastructure for single MediaStreamSource for all of them. After that, I thought about investigating on how to make ALAC playback: there is an open source codec, but it also requires demuxing samples from MP4 container, and that's where I'm stuck.

**Comment by brabebhin** [comment]
Aren't mpeg codecs and containers pretended? 

One of the things people want from windows phone is LAME decoder for mp3 files.

**Comment by Alovchin91** [comment]
@mcosmin222 Pretended?..
Okay, so let's add the fourth codec to our list :)

**Comment by brabebhin** [comment]
Ape xD

**Comment by Alovchin91** [comment]
@mcosmin222 Nah, Monkey audio requires some kind of driver of I remember it correctly.

**Comment by brabebhin** [comment]
Technicaly, moliplayer can play ape
