### ISSUE TITLE
Album art

### ISSUE THREAD

**Issue by brabebhin** [Alovchin91/vorbis-winrt#3]
As I was saying.
this is where you will find the ogg file

https://onedrive.live.com/redir?resid=8C149B080B3B968F!269367&authkey=!AHOwdXNQAvLGd8M&ithint=folder%2copus

It seems to be an issue with the METADATA_BLOCK_PICTURE comment.

**Comment by brabebhin** [comment]
So tthe comments one gets after calling .Comment() return some weird Arabic characters in addition to the actual metadata.

**Comment by Alovchin91** [comment]
@mcosmin222 Hmm, funny, I thought I fixed that bug. Those weird characters are actually the contents of your RAM :) The string is not null terminated due to a bug and thus you see the memory behind the bounds of the string. I'll fix this shortly.

**Comment by brabebhin** [comment]
Well it is kinda funny that there are always the same weird Arabic characters.
I though the encoder was putting them there for some twisted purpose. Apparently, only ogg files have this problem (couldn't get flac files to return metadata yet).

**Comment by Alovchin91** [comment]
@mcosmin222 Yes, this is my bug :( I fixed it, take the latest sources. I'll check the other projects tomorrow.

**Comment by Alovchin91** [comment]
@mcosmin222 After the fix I can decode Base64 string of picture in your files, but the decoder then crashes with OutOfMemoryException :) I'm pretty sure you definitely should not decode the picture in the background task.

**Comment by brabebhin** [comment]
Well that is what I am trying to avoid. Only read title and artist in audio task and get the picture in a different task. They do not share memory, so you can basically get 32MB of memory in the background. 

By the way, that picture is evil. It is a high resolution one captured during my classes. It is almost 1MB size.

**Comment by brabebhin** [comment]
I think the other libraries are working fine.
